-- SELECT P.65 연습문제
-- 예제 01번
SELECT ENAME, SALARY, SALARY+300 AS "ADD_SALARY" FROM EMPLOYEE;

-- 예제 02번
SELECT ENAME, SALARY, SALARY*12+100 AS "12_SALARY" FROM EMPLOYEE ORDER BY SALARY DESC;

-- 예제 03번
SELECT ENAME, SALARY FROM EMPLOYEE WHERE SALARY > 2000 ORDER BY SALARY DESC;

-- 예제 04번
SELECT ENAME, DNO FROM EMPLOYEE WHERE ENO = 7788;

-- 예제 05번
SELECT ENAME, SALARY FROM EMPLOYEE WHERE 2000 >= SALARY OR SALARY >= 3000;

SELECT ENAME, SALARY FROM EMPLOYEE WHERE SALARY NOT BETWEEN 2000 AND 3000;

-- 예제 06번
SELECT ENAME, JOB, HIREDATE FROM EMPLOYEE WHERE HIREDATE BETWEEN '1981/02/20' AND '1981/05/01';

-- 예제 07번
SELECT ENAME, DNO FROM EMPLOYEE WHERE DNO IN(20,30) ORDER BY ENAME ASC;

-- 예제 08번
SELECT ENAME, SALARY, DNO FROM EMPLOYEE WHERE SALARY BETWEEN 2000 AND 3000 AND DNO IN(20,30) ORDER BY ENAME ASC;

-- 예제 09번
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE HIREDATE LIKE '81%';

-- 예제 10번
SELECT ENAME, JOB FROM EMPLOYEE WHERE MANAGER IS NULL;

-- 예제 11번
SELECT ENAME, SALARY, COMMISSION FROM EMPLOYEE WHERE COMMISSION IS NOT NULL;

-- 예제 12번
SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE '__R%';

-- 예제 13번
SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE '%A%' AND ENAME LIKE '%E%';

-- 예제 14번
SELECT ENAME, JOB, SALARY FROM EMPLOYEE WHERE JOB IN('CLERK','SALESMAN') AND SALARY NOT IN (1600, 950, 1300);

-- 예제 15번
SELECT ENAME, SALARY, COMMISSION FROM EMPLOYEE WHERE COMMISSION >= 500;
